[package]
name = "radix-mlp-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
radix_mlp = { path = "../package" }
pyo3 = { version = "0.27", features = ["extension-module", "abi3-py310"] }
numpy = "0.27"